"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()  # carrega o .env da raiz do projeto

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)s@fwddpff6@ew6qso8i!_tkz_=ud10z8tb2!1brr4_r8myb#e"

# SECURITY WARNING: don't run with debug turned on in production!
# Defina DEBUG=False e configure ALLOWED_HOSTS antes de ir para produção.
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "app",

    "app.features.usuarios",
    "app.features.produtos",
    "app.features.alertas",
    "app.features.busca_inteligente",
    "app.features.historico_precos",
    "app.features.email",

    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os

if os.environ.get("USE_MONGO", "0") == "1":
    DATABASES = {
        "default": {
            "ENGINE": "djongo",
            "NAME": "site_promocoes_db",
            "ENFORCE_SCHEMA": False,
            "CLIENT": {
                "host": os.environ.get("MONGO_HOST", "mongodb://db:27017"),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = "static/"
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CORS_ALLOW_ALL_ORIGINS = True  # Em produção, substitua por CORS_ALLOWED_ORIGINS

CORS_ALLOWED_ORIGINS = [
    "https://site-promocoes-frontend.vercel.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}


BASE_DIR = Path(__file__).resolve().parent.parent

# Configurações do Google OAuth
# Em produção (ex: Render), estas variáveis podem ser strings JSON em variáveis de ambiente
GOOGLE_CLIENT_SECRET_JSON = os.environ.get('GOOGLE_CLIENT_SECRET_JSON')
GOOGLE_TOKEN_JSON = os.environ.get('GOOGLE_TOKEN_JSON')

GOOGLE_CLIENT_SECRET_FILE = os.path.join(BASE_DIR, 'config', 'client_secret.json')
GOOGLE_TOKEN_FILE = os.path.join(BASE_DIR, 'config', 'token.json')

# O e-mail que vai disparar as mensagens
EMAIL_USER = os.environ.get('EMAIL_USER', 'seu-email@gmail.com')
# URL do frontend (usada em links nos emails)
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")

# Google Client ID para autenticação no frontend/backend
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')

# JWT Secret Key
JWT_SECRET = os.environ.get("JWT_SECRET", SECRET_KEY)
JWT_ALGORITHM = "HS256"

